### ISSUE TITLE
Crash? Crash.

### ISSUE THREAD

**Issue by ajthemacboy** [TallWorlds/CubicChunks#33]
Here's the report, it happens when I create a new world: http://pastebin.com/89bZ6Ad8

**Comment by cuchaz** [comment]
What version of Tall Worlds Mod are you using? What Version of M3L are you using? Posting your log would help too.

I should really hack the crash reports to include these things...

**Comment by wordandahalf** [comment]
@cuchaz It seems if you use M3L v0.3 & TWM it crashes with that error.
(To solve, uninstall M3L v0.3, and install M3L v0.2)

**Comment by cuchaz** [comment]
Again, what version of Tall Worlds Mod? If you're mismatching versions between TWM and M3L, that probably won't work.

**Comment by mikesmiffy128** [comment]
Actually, looking at the current TWM build.gradle, the M3L dependency is 0.2 rather than 0.3, and the error thrown relates to binary compatibility (I think), so there was probably a breaking change in M3L. This could be considered an M3L bug I guess, depending on whether backwards compatibility is something you care about at this point.

Edit: Made sentences make sense. I should stop replying on mobile.

**Comment by Niko-sk2x** [comment]
Latest version required M3L 0.3 (it's 0.2 in build.gradle because until recently 0.3 wasn't available in maven repository).
Previous beta release of TWM won't work with new M3L (compatibility breaking changes, Cuchaz added 2 methid to some interface which aren't implemented in older version). I don't think backwards compatibility (or any compatibility at all, except what is required to actually run it) is Cuchaz's priority in this development stage.

**Comment by cuchaz** [comment]
Yup. Backwards compatibility is not a goal at this point. These are 0.x releases.
